### ISSUE TITLE
Analyze and fix OOM Killer issues on CBI

### ISSUE THREAD

**Issue by cdietrich** [eclipse/xtext#1431]
Analyze and fix OOM Killer issues on CBI

https://jenkins.eclipse.org/xtext/job/xtext-xtend/job/master/18/console

```
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:1.4.0:test (default-test) on project org.eclipse.xtend.ide.tests: An unexpected error occured while launching the test runtime (return code 137). See log /home/jenkins/workspace/xtext-xtend_master-CZ6MQ7K3F54I6ECVAJOY5S5BWV6SPAS3CFPK73ZFQFHMBDDXMCYA/org.eclipse.xtend.ide.tests/target/work/data/.metadata/.log for details. -> [Help 1]
```

**Comment by cdietrich** [comment]
i also wonder if there is something in 4.12 that leads to increased memory usages

**Comment by kthoms** [comment]
See discussions on cbi-dev and CBI FAQ
- https://wiki.eclipse.org/Jenkins#What_is_killing_my_build.3F_I.27m_using_custom_containers.21
- https://www.eclipse.org/lists/cbi-dev/msg02102.html
- https://www.eclipse.org/lists/cbi-dev/msg02100.html

**Comment by kthoms** [comment]
Likely a temporary issue:

https://ci-staging.eclipse.org/xtext/user/karsten.thoms@itemis.de/my-views/view/kt_issue1431/job/xtext-maven/job/kt_issue1431/2/console
```
ERROR: Error cloning remote repo 'origin'
hudson.plugins.git.GitException: Command "/usr/bin/git fetch --no-tags --progress https://github.com/eclipse/xtext-maven.git +refs/heads/kt_issue1431:refs/remotes/origin/kt_issue1431" returned status code 128:
stdout: 
stderr: fatal: unable to access 'https://github.com/eclipse/xtext-maven.git/': Could not resolve host: github.com
```

**Comment by kthoms** [comment]
xtext-eclipse has more resource requirements than the others:
https://ci-staging.eclipse.org/xtext/job/xtext-eclipse/job/kt_issue1431/5/console
```
[INFO] org.eclipse.xtext.tycho.parent ..................... SUCCESS [ 41.309 s]
[INFO] org.eclipse.xtext.target ........................... SUCCESS [  3.695 s]
[INFO] org.eclipse.xtext.tycho.plugin.parent .............. SUCCESS [  0.093 s]
[INFO] org.eclipse.xtext.tycho.feature.parent ............. SUCCESS [  0.007 s]
[INFO] Xtext Eclipse tests plugins parent ................. SUCCESS [  0.094 s]
[INFO] org.eclipse.xtext.activities ....................... FAILURE [ 16.804 s]
...
[ERROR] Java heap space -> [Help 1]
```

**Comment by kthoms** [comment]
Specifying more memory (3Gi) for resource limits did not help.

**Comment by kthoms** [comment]
Occurs for xtext-core although resource constraints had been set. Strangely this did not occur in previous builds.

https://ci-staging.eclipse.org/xtext/view/Xtext-release/job/xtext-core/job/milestone_2.18.0.Beta/5/console
```
> Task :org.eclipse.xtext.util:generateXtext
./1-gradle-build.sh: line 15:    21 Killed                  ./gradlew clean cleanGenerateXtext build createLocalMavenRepo -PuseJenkinsSnapshots=true -PJENKINS_URL=$JENKINS_URL -PcompileXtend=true -PignoreTestFailures=true --refresh-dependencies --continue $@
```

**Comment by cdietrich** [comment]
hmmmm
is this the virtual machine itself or the host?

**Comment by kthoms** [comment]
It seems that using defaults for CPU utilization should be enough. We should try to revert this setting for those Jenkinsfile that have already been merged.

>If you do not specify a CPU limit for a Container, then one of these situations applies:
>    The Container has no upper bound on the CPU resources it can use. The Container could use all of the CPU resources available on the Node where it is running.
>    The Container is running in a namespace that has a default CPU limit, and the Container is automatically assigned the default limit. Cluster administrators can use a LimitRange to specify a default value for the CPU limit.

https://kubernetes.io/docs/tasks/configure-pod-container/assign-cpu-resource/#if-you-do-not-specify-a-cpu-limit

**Comment by kthoms** [comment]
Good article about memory utilization of Java in containers:
https://medium.com/adorsys/jvm-memory-settings-in-a-container-environment-64b0840e1d9e

**Comment by kthoms** [comment]
Activation of `+PrintFlagsFinal` reveals that the Gradle JVM is running with MaxRAM=137438953472 bytes (128GB).
The file `/sys/fs/cgroup/memory/memory.limit_in_bytes` contains the actual available memory to the container, which is 2147483648 (2GB).
So the VM eats far more memory than it is available to the container.
As the article suggests it would be possible to define a ratio from the container memory for `MaxRAM` by evaluating the value from `/sys/fs/cgroup/memory/memory.limit_in_bytes`. This has to be set for all Java invocations, e.g. by setting `GRADLE_OPTS` and `MAVEN_OPTS`.

**Comment by cdietrich** [comment]
i assume a `gradle.properties` would help too and could also help locally
```
org.gradle.jvmargs=-Xmx2G
```

**Comment by kthoms** [comment]
Using `-XX:MaxRAMPercentage` is the more easier approach than the one described above. This JVM option has been added to Java 8 with a recent release.
There is still a problem with executing UI tests. They are configured with `-Xmx2g` by default. When the container as max. 2g and the heap is allowed to consume the same, the JVM has noot enough memory. I'll try to leverage `-XX:MaxRAMPercentage` also for the test runtime.

**Comment by cdietrich** [comment]
i don’t think its a good idea to use that percentage on a machine with 128 go ram an on ones with 4 gb. To me it makes no sense

**Comment by cdietrich** [comment]
move to 2.19

**Comment by cdietrich** [comment]
still an issue here: https://ci-staging.eclipse.org/xtext/job/xtext-umbrella/job/ade-newbuild/

**Comment by kthoms** [comment]
@Hejado and I did some experiments with resources. Given the following pipeline:

```
pipeline {
  agent {
    kubernetes {
      label 'xtext-resources-' + env.BUILD_NUMBER
      defaultContainer 'xtext-buildenv'
      yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: 'eclipsecbi/jenkins-jnlp-agent'
    args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
    resources:
      limits:
        memory: "0.4Gi"
        cpu: "0.2"
      requests:
        memory: "0.4Gi"
        cpu: "0.2"
    volumeMounts:
    - mountPath: /home/jenkins/.ssh
      name: volume-known-hosts
  - name: xtext-buildenv
    image: docker.io/smoht/xtext-buildenv:0.7
    tty: true
    resources:
      limits:
        memory: "3.6Gi"
        cpu: "1.0"
      requests:
        memory: "3.6Gi"
        cpu: "1.0"
    volumeMounts:
    - name: settings-xml
      mountPath: /home/jenkins/.m2/settings.xml
      subPath: settings.xml
      readOnly: true
    - name: m2-repo
      mountPath: /home/jenkins/.m2/repository
    - name: volume-known-hosts
      mountPath: /home/jenkins/.ssh
  volumes:
  - name: volume-known-hosts
    configMap:
      name: known-hosts
  - name: settings-xml
    configMap: 
      name: m2-dir
      items:
      - key: settings.xml
        path: settings.xml
  - name: m2-repo
    emptyDir: {}
    '''
    }
  }
  
   
  stages {
    stage('Test CPU & RAM') {
      steps {
        sh ''' 
         

         echo "MEMORY: $(($(cat /sys/fs/cgroup/memory/memory.limit_in_bytes ) / 1024 / 1024)) MB"
         echo "CPU: $(cat /sys/fs/cgroup/cpu/cpu.shares)"

         sleep 10m
       
      '''}
    }
  }
}
```

With tweaking `memory` and `cpu` settings we observed the following:

```
1) Mem: 1Gi + 512 Mi; CPU 1 + 0.2 => 2 Executors
2) Mem: 3Gi + 512 Mi; CPU 1 + 0.2 => 2 Executors
3) Mem: 3Gi + 512 Mi; CPU 1.5 + 0.2 => 1 Executor
4) Mem: 4Gi + 512 Mi; CPU 1 + 0.2 => 1 Executor
5) Mem: 3.5Gi + 512 Mi; CPU 1 + 0.2 => 2 Executors 
6) Mem: 3.7Gi + 0.3Gi; CPU 1.15 + 0.05 => 0 Executors (Agent start provisioning, but fail)
7) Mem: 3.5Gi + 0.5Gi; CPU 1.1 + 0.1 => 2 Executors
8) Mem: 3.5Gi + 0.5Gi; CPU 0.9 + 0.4 => 1 Executor (faster startup of agent)
9) Mem: 3.6Gi + 0.4Gi; CPU 1 + 0.2 => 2 Executors
10) Mem: 3.6Gi + 0.4Gi; CPU 1.1 + 0.1 => 2 Executors (agent provisioning: 2:18 min)
11) Mem: 3.6Gi + 0.4Gi; CPU 1.0 + 0.2 => 2 Executors (agent provisioning: 1:37 min)
```

As a result, setup number 11 seems to make optimal usage of cpu and memory.
